# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'hsdmin/coredockercicddemo:$(build.buildNumber)'

steps:

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    command: Build an image
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: MuraliDockerCICD
    dockerFile: Dockerfile
    imageName: $(imageName)
    restartPolicy: always